import type { DatasetKey, DatasetSort } from "./types.ts";

const SKU_SELECT_COLUMNS = [
  "id",
  "settlement_report_id",
  "elaboration_run_id",
  "order_id",
  "adjustment_id",
  "shipment_id",
  "posted_date",
  "currency",
  "company_id",
  "sku_company_assignment_id",
  "company_fee_rule_id",
  "marketplace_id",
  "marketplace_name",
  "amz_sku",
  "settlement_category",
  "handling_method",
  "join_method",
  "allocation_basis",
  "allocation_driver",
  "allocation_driver_unit",
  "elaborated_amount",
  "difference_amount",
  "settlement_amount",
  "fee_rate_percent",
  "selbox_fee",
  "company_payable",
  "created_at",
  "units_sold",
  "units_returned",
  "net_units_sold",
  "average_sales_price",
  "per_unit_breakdown",
  "sales_occurrence_count",
  "return_occurrence_count",
  "product_sales",
  "product_refunds",
  "liquidations_proceeds",
  "shipping_credits",
  "shipping_refunds",
  "gift_wrap_credits",
  "gift_wrap_refunds",
  "promotional_rebates",
  "sales_tax",
  "marketplace_withheld_tax",
  "referral_fees",
  "fba_fulfillment_fees",
  "base_fulfillment_fees",
  "low_inventory_level_fees",
  "per_item_selling_fees",
  "closing_fees",
  "fba_prep_fees",
  "digital_services_fees",
  "amazon_fee_taxes",
  "liquidations_brokerage_fees",
  "refund_administration_fees",
  "shipping_chargebacks",
  "other_amazon_fees",
  "advertising_cost",
  "sponsored_products_charges",
  "sponsored_brands_charges",
  "sponsored_display_charges",
  "advertising_refund",
  "fba_storage_fees",
  "fba_aged_inventory_fees",
  "fba_inbound_placement_fees",
  "inbound_transportation_fees",
  "removal_disposal_fees",
  "removal_fees",
  "disposal_fees",
  "inventory_reimbursements",
  "unmapped_amount",
  "cost_of_goods_sold",
  "shipping_to_amazon_cost",
  "mfn_fulfillment_cost",
  "mfn_storage_cost",
  "miscellaneous_cost",
  "other_elaborated_amount",
] as const;

const ACCOUNT_SELECT_COLUMNS = [
  "id",
  "settlement_report_id",
  "elaboration_run_id",
  "order_id",
  "adjustment_id",
  "shipment_id",
  "posted_date",
  "currency",
  "company_id",
  "marketplace_id",
  "marketplace_name",
  "amz_sku",
  "category_code",
  "pnl_treatment",
  "handling_method",
  "join_method",
  "allocation_basis",
  "allocation_driver",
  "allocation_driver_unit",
  "unassigned_reason",
  "elaborated_amount",
  "difference_amount",
  "settlement_amount",
  "selbox_fee",
  "company_payable",
  "created_at",
] as const;

const EXCLUDED_SELECT_COLUMNS = [
  "id",
  "settlement_report_id",
  "elaboration_run_id",
  "adjustment_id",
  "shipment_id",
  "posted_date",
  "currency",
  "category_code",
  "handling_method",
  "allocation_basis",
  "unassigned_reason",
  "settlement_amount",
  "difference_amount",
  "created_at",
] as const;

const SKU_SORT_COLUMNS = [
  "id",
  "order_id",
  "posted_date",
  "currency",
  "company_id",
  "marketplace_name",
  "amz_sku",
  "settlement_category",
  "handling_method",
  "join_method",
  "allocation_basis",
  "elaborated_amount",
  "difference_amount",
  "settlement_amount",
  "fee_rate_percent",
  "selbox_fee",
  "company_payable",
  "units_sold",
  "units_returned",
  "net_units_sold",
  "average_sales_price",
  "product_sales",
  "product_refunds",
  "referral_fees",
  "fba_fulfillment_fees",
  "promotional_rebates",
  "sponsored_products_charges",
  "fba_storage_fees",
  "cost_of_goods_sold",
  "miscellaneous_cost",
] as const;

const ACCOUNT_SORT_COLUMNS = [
  "id",
  "order_id",
  "posted_date",
  "currency",
  "company_id",
  "marketplace_name",
  "amz_sku",
  "category_code",
  "pnl_treatment",
  "handling_method",
  "join_method",
  "allocation_basis",
  "unassigned_reason",
  "elaborated_amount",
  "difference_amount",
  "settlement_amount",
  "selbox_fee",
  "company_payable",
] as const;

const EXCLUDED_SORT_COLUMNS = [
  "id",
  "adjustment_id",
  "shipment_id",
  "posted_date",
  "currency",
  "category_code",
  "handling_method",
  "allocation_basis",
  "unassigned_reason",
  "settlement_amount",
  "difference_amount",
] as const;

export interface DatasetConfig {
  label: string;
  endpoint: string;
  selectColumns: readonly string[];
  searchColumns: readonly string[];
  sortColumns: readonly string[];
  defaultSort: DatasetSort;
}

export const DATASET_CONFIG = {
  sku: {
    label: "SKU Economics",
    endpoint: "sku_economics_transactions",
    selectColumns: SKU_SELECT_COLUMNS,
    searchColumns: [
      "order_id",
      "adjustment_id",
      "shipment_id",
      "currency",
      "marketplace_name",
      "amz_sku",
      "settlement_category",
      "handling_method",
      "join_method",
      "allocation_basis",
    ],
    sortColumns: SKU_SORT_COLUMNS,
    defaultSort: { column: "posted_date", direction: "desc" },
  },
  account: {
    label: "Account-level",
    endpoint: "account_level_settlement_transactions",
    selectColumns: ACCOUNT_SELECT_COLUMNS,
    searchColumns: [
      "order_id",
      "adjustment_id",
      "shipment_id",
      "currency",
      "marketplace_name",
      "amz_sku",
      "category_code",
      "pnl_treatment",
      "handling_method",
      "join_method",
      "allocation_basis",
      "unassigned_reason",
    ],
    sortColumns: ACCOUNT_SORT_COLUMNS,
    defaultSort: { column: "posted_date", direction: "desc" },
  },
  excluded: {
    label: "Excluded Movements",
    endpoint: "excluded_settlement_movements",
    selectColumns: EXCLUDED_SELECT_COLUMNS,
    searchColumns: [
      "adjustment_id",
      "shipment_id",
      "currency",
      "category_code",
      "handling_method",
      "allocation_basis",
      "unassigned_reason",
    ],
    sortColumns: EXCLUDED_SORT_COLUMNS,
    defaultSort: { column: "posted_date", direction: "desc" },
  },
} as const satisfies Record<DatasetKey, DatasetConfig>;
