"""Canonical Amazon FBA report type identifiers."""

FBA_AGED_STORAGE_FEE_REPORT = "GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA"
FBA_REMOVAL_ORDER_DETAIL_REPORT = "GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA"

__all__ = [
    "FBA_AGED_STORAGE_FEE_REPORT",
    "FBA_REMOVAL_ORDER_DETAIL_REPORT",
]
