import { expect, test } from "@playwright/test";
import { mockSupabase, signIn, captureResponsiveReview } from "./fixtures.mjs";

test("a zero report displays without a currency, is reused, and is not regenerated by source refresh", async ({
  page,
}, testInfo) => {
  await page.clock.install();
  const fixture = await mockSupabase(page);
  const company = "0198b50b-701a-7000-8000-000000000001";
  fixture.roles["member-a"] = "operator";
  fixture.companyIds["member-b"] = company;
  fixture.companyNames[company] = "Monthly Company";
  fixture.payoutGeneratedReport = {
    seller_namespace: null,
    currency: null,
    preprocess_version: null,
    source_amount: "0",
    fee_amount: "0",
    company_amount: "0",
    component_count: "0",
    reconciliation_count: "0",
    settlement_version_count: "2",
    data_kiosk_version_count: "1",
    terms_version_count: "1",
  };
  await signIn(page);
  await page.getByRole("tab", { name: "Payout reports", exact: true }).click();
  await page.getByLabel("Report company").selectOption(company);
  await page.getByLabel("Report month").fill("2026-06");
  await page.getByRole("button", { name: "Generate payout reports" }).click();
  await expect(page.getByText("1 payout report saved.", { exact: true })).toBeVisible();
  await expect(page.getByRole("cell", { name: "0", exact: true })).toHaveCount(3);
  await page.getByRole("cell", { name: "0", exact: true }).first().click();
  const drawer = page.getByRole("dialog", { name: "Selected row details" });
  await expect(drawer.locator(".detail-grid").getByText("0", { exact: true })).toHaveCount(3);
  await expect(drawer.getByText("No saved marketplace amounts.", { exact: true })).toBeVisible();
  await expect(
    drawer.getByText("No saved details for this section.", { exact: true }),
  ).toBeVisible();
  await expect(drawer.getByRole("columnheader")).toHaveCount(0);
  await expect(drawer.getByText("Seller reconciliation", { exact: true })).toHaveCount(0);
  await expect(drawer.getByText(/\b0 [A-Z]{3}\b/)).toHaveCount(0);
  await captureResponsiveReview(page, testInfo, "zero-payout-report");
  await page.getByRole("button", { name: "Close row details" }).click();
  await page.getByRole("button", { name: "Generate payout reports" }).click();
  await expect(page.getByRole("status").filter({ hasText: "payout report" })).toHaveText(
    "Reports unchanged. No new reports saved. 1 existing payout report reused.",
  );
  expect(fixture.payoutRows).toHaveLength(1);
  expect(fixture.generatedPayouts).toHaveLength(2);

  const completedPolls = () => fixture.revisionRequests.filter(({ completed }) => completed).length;
  const pollsBefore = completedPolls();
  fixture.revisions.settlement = "1";
  fixture.revisions.data_kiosk = "1";
  fixture.revisions.fees = "1";
  await page.clock.fastForward(60_000);
  await expect.poll(completedPolls).toBeGreaterThan(pollsBefore);
  await expect(page.getByText("Updating…", { exact: true })).toBeHidden();
  expect(fixture.generatedPayouts).toHaveLength(2);
  expect(fixture.payoutRows).toHaveLength(1);
  await expect(page.getByRole("cell", { name: "0", exact: true })).toHaveCount(3);
});
